### ISSUE TITLE
 Error: json: cannot unmarshal number 64687125982 into Go struct field pStats.Results.Bytes of type int

### ISSUE THREAD

**Issue by lukaszsedek** [bluecmd/fortigate_exporter#56] opened 2021-03-11 08:56 UTC
When I run fortigate_exporter I see this error:

`2021/03/11 08:50:12 Error: json: cannot unmarshal number 64687125982 into Go struct field pStats.Results.Bytes of type int
2021/03/11 08:50:13 Probe of "https://192.168.30.1" failed, took 0.766 seconds`

**Comment by bluecmd** [comment] 2021-03-11 11:39
That value is 36 bits it seems, so likely the int type defaults to 32-bit for this particular build.

Changing to int64 might be the correct thing here, worst case float64. Should be easy to repro in test cases.

Thanks for the report!

**Comment by bluecmd** [comment] 2021-03-12 15:40
@lukaszsedek can you try with the latest version and see if the issue is gone for you?

**Comment by secustor** [comment] 2021-03-17 16:24
Closing this issue as we have merged code which should fix this and haven't received an answer regarding the current state of the issue.   

If the issue is still their, feel free to reopen this issue.

**Closed by secustor** 2021-03-17 16:24 UTC
Labels: bug
